<?php

/**
 * Created by PhpStorm.
 * User: e
 * Date: 2015-05-27
 * Time: 15:17
 */
class Dingdan extends ODingdan {
    public $fileField = '';

    public function attributeLabels() {
        return array(
            'id' => 'ID',
            'pingtai' => '平台',
            'laiyuan' => '来源',
            'partner' => 'Partner',
            'user_id' => '商家账号',
            'order_type' => 'Order Type',
            'order_type_explain' => 'Order Type Explain',
            'zhifufangshi' => '支付方式',
            'sys_dingdanbianhao' => '系统订单编号',
            'dingdanbianhao' => '来源订单编号',
            'fenjiandanhao' => '分拣单号',
            'suoshukehu' => '所属客户',
            'kehubianhao' => '客户编号',
            'suoshucangku' => '所属仓库',
            'dingdanjine' => '订单金额',
            'shouhuoren' => '收货人',
            'youbian' => '邮编',
            'sheng' => '省',
            'shi' => '市',
            'qu' => '区',
            'dianhua' => '电话',
            'shouji' => '手机',
            'dizhi' => '地址',
            'fahuoren' => '发货人',
            'fahuo_youbian' => '发货邮编',
            'fahuo_sheng' => '发货省',
            'fahuo_shi' => '发货市',
            'fahuo_qu' => '发货区',
            'fahuo_dizhi' => '发货地址',
            'fahuo_shouji' => '发货手机',
            'fahuo_dianhua' => '发货电话',
            'attributes' => '订单属性',
            'remark' => '备注',
            'order_create_time' => '来源订单创建时间',
            'order_flag' => 'Order Flag',
            'order_flag_explain' => 'Order Flag Explain',
            'alipay_no' => 'Alipay No',
            'fapiao_type' => '发票类型',
            'fapiao_taitou' => '发票抬头',
            'fapiao_jine' => '发票金额',
            'fapiao_neirong' => '发票内容',
            'youhuiquan' => '优惠券',
            'kouyouhuiquan' => '扣优惠券',
            'yunfei' => '运费',
            'yishoukuan' => '已收款',
            'yingfukuan' => '应付款',
            'zongshuliang' => '总数量',
            'total_amount' => '总金额',
            'payable_amount' => '已付款',
            'yingshou_amount' => '应收款',
            'shishou_amount' => '实收款',
            'daishou_amount' => '代收款',
            'service_fee' => '服务费',
            'schedule_type' => 'Schedule Type',
            'schedule_type_explain' => 'Schedule Type Explain',
            'schedule_start' => 'Schedule Start',
            'schedule_end' => 'Schedule End',
            'buyliuyan' => '买家留言',
            'saleliuyan' => '卖家留言',
            'peisongshang' => '配送商',
            'wuliudanhao' => '物流单号',
            'zhongliang' => '重量',
            'peisongfei' => '配送费',
            'lururen' => '录入人',
            'createtime' => '录入时间',
            'fapiaohao' => '发票号',
            'invoice_info' => 'Invoice Info',
            'order_remark' => 'Order Remark',
            'order_start_time' => 'Order Start Time',
            'jingdong_chuku' => '京东出库',
            'bufayuanyin' => 'Bufayuanyin',
            'kefu_time' => 'Kefu Time',
            'chengzhongren' => '称重人',
            'chengzhong_time' => '称重时间',
            'jiaojiedanhao' => '交接单号',
            'jiaojiedanhao_time' => '生成交接单号时间',
            'jiaojiedanhao_man' => '生成交接单号人',
            'jiaojieren' => '交接人',
            'jiaojietime' => '交接时间',
            'zuofei' => '作废',
            'zuofei_man' => '作废人',
            'zuofei_time' => '作废时间',
            'huifu_man' => '恢复人',
            'huifu_time' => '恢复时间',
            'ispost_luodipei' => 'Ispost Luodipei',
            'ispost_luodipei_time' => 'Ispost Luodipei Time',
            'ispost_luodipei_man' => 'Ispost Luodipei Man',
            'ispost_luodipei_back' => 'Ispost Luodipei Back',
            'ispost_luodipei_time_back' => 'Ispost Luodipei Time Back',
            'zhuangtai' => '状态',
        );
    }

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }
}